#!/usr/bin/env bash

# ADD ADDITIONAL FEATURES
# =========================
# PYTHON
sudo -s apt-get update -y \
  && sudo -s apt-get install -y python3-pip libffi-dev idle3 \
  && sudo pip3 install docker-compose \
  && sudo -s pip3 install --no-cache-dir --upgrade pip \
  && sudo -s pip3 --disable-pip-version-check --no-cache-dir install -r ./python/requirements.txt